# Import libraries

In [1]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.metrics import confusion_matrix, accuracy_score

# Read the dataset

In [3]:
#Import Dataset
ds= pd.read_csv("dataset_website.csv") 
ds.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    1           -1               1           -1             -1            1   
1   -1           -1              -1           -1             -1            0   
2    1           -1               0            0             -1            0   
3    1            0               1           -1             -1            0   
4   -1           -1               1           -1              0            0   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           1              1                  0       0  
1           1              1                  1       1  
2          -1              1                  0       1  
3           1              1                  0       0  
4          -1              1                  0       1

# Handling Null

In [4]:
#Analysing the data using pandas and Checking if the dataset contains any Null values. 
ds.info() 
ds.isnull().any () #no null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353 entries, 0 to 1352
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SFH                1353 non-null   int64
 1   popUpWidnow        1353 non-null   int64
 2   SSLfinal_State     1353 non-null   int64
 3   Request_URL        1353 non-null   int64
 4   URL_of_Anchor      1353 non-null   int64
 5   web_traffic        1353 non-null   int64
 6   URL_Length         1353 non-null   int64
 7   age_of_domain      1353 non-null   int64
 8   having_IP_Address  1353 non-null   int64
 9   Result             1353 non-null   int64
dtypes: int64(10)
memory usage: 105.8 KB


SFH                  False
popUpWidnow          False
SSLfinal_State       False
Request_URL          False
URL_of_Anchor        False
web_traffic          False
URL_Length           False
age_of_domain        False
having_IP_Address    False
Result               False
dtype: bool

# Splitting the data

In [6]:
#Splitting data as independent and dependent 
#removing index column in independent dataset
x=ds.iloc[:,1:31].values
y=ds.iloc[:, -1].values 
print(x,y)

[[-1  1 -1 ...  1  0  0]
 [-1 -1 -1 ...  1  1  1]
 [-1  0  0 ...  1  0  1]
 ...
 [ 0 -1 -1 ... -1  0  1]
 [ 0  1  0 ...  1  0  1]
 [ 0  1  1 ... -1  0 -1]] [ 0  1  1 ...  1  1 -1]


In [9]:
#Splitting data into train and test 
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)