# Import libraries

In [12]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.metrics import confusion_matrix, accuracy_score

# Read the dataset

In [13]:
#Import Dataset
ds= pd.read_csv("dataset_website.csv") 
ds.head()

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  web_traffic  \
0    1           -1               1           -1             -1            1   
1   -1           -1              -1           -1             -1            0   
2    1           -1               0            0             -1            0   
3    1            0               1           -1             -1            0   
4   -1           -1               1           -1              0            0   

   URL_Length  age_of_domain  having_IP_Address  Result  
0           1              1                  0       0  
1           1              1                  1       1  
2          -1              1                  0       1  
3           1              1                  0       0  
4          -1              1                  0       1

In [14]:
ds

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
0       1           -1               1           -1             -1   
1      -1           -1              -1           -1             -1   
2       1           -1               0            0             -1   
3       1            0               1           -1             -1   
4      -1           -1               1           -1              0   
...   ...          ...             ...          ...            ...   
1348   -1           -1              -1           -1             -1   
1349   -1            0               1            0             -1   
1350   -1            0              -1           -1             -1   
1351    0            0               1            0              0   
1352    1            0               1            1              1   

      web_traffic  URL_Length  age_of_domain  having_IP_Address  Result  
0               1           1              1                  0       0  
1               0           1              1                  1       1  
2               0          -1              1                  0       1  
3               0           1              1                  0       0  
4               0          -1              1                  0       1  
...           ...         ...            ...                ...     ...  
1348           -1           0              1                  0       1  
1349            0           0              1                  0      -1  
1350            0          -1             -1                  0       1  
1351            0          -1              1                  0       1  
1352            0          -1             -1                  0      -1  

[1353 rows x 10 columns]

# Handling Null

In [15]:
#Analysing the data using pandas and Checking if the dataset contains any Null values. 
ds.info() 
ds.isnull().any () #no null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1353 entries, 0 to 1352
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SFH                1353 non-null   int64
 1   popUpWidnow        1353 non-null   int64
 2   SSLfinal_State     1353 non-null   int64
 3   Request_URL        1353 non-null   int64
 4   URL_of_Anchor      1353 non-null   int64
 5   web_traffic        1353 non-null   int64
 6   URL_Length         1353 non-null   int64
 7   age_of_domain      1353 non-null   int64
 8   having_IP_Address  1353 non-null   int64
 9   Result             1353 non-null   int64
dtypes: int64(10)
memory usage: 105.8 KB


SFH                  False
popUpWidnow          False
SSLfinal_State       False
Request_URL          False
URL_of_Anchor        False
web_traffic          False
URL_Length           False
age_of_domain        False
having_IP_Address    False
Result               False
dtype: bool

In [16]:
ds = ds.replace('[\d.]','', regex=True).astype(float)
ds

SFH  popUpWidnow  SSLfinal_State  Request_URL  URL_of_Anchor  \
0     1.0         -1.0             1.0         -1.0           -1.0   
1    -1.0         -1.0            -1.0         -1.0           -1.0   
2     1.0         -1.0             0.0          0.0           -1.0   
3     1.0          0.0             1.0         -1.0           -1.0   
4    -1.0         -1.0             1.0         -1.0            0.0   
...   ...          ...             ...          ...            ...   
1348 -1.0         -1.0            -1.0         -1.0           -1.0   
1349 -1.0          0.0             1.0          0.0           -1.0   
1350 -1.0          0.0            -1.0         -1.0           -1.0   
1351  0.0          0.0             1.0          0.0            0.0   
1352  1.0          0.0             1.0          1.0            1.0   

      web_traffic  URL_Length  age_of_domain  having_IP_Address  Result  
0             1.0         1.0            1.0                0.0     0.0  
1             0.0         1.0            1.0                1.0     1.0  
2             0.0        -1.0            1.0                0.0     1.0  
3             0.0         1.0            1.0                0.0     0.0  
4             0.0        -1.0            1.0                0.0     1.0  
...           ...         ...            ...                ...     ...  
1348         -1.0         0.0            1.0                0.0     1.0  
1349          0.0         0.0            1.0                0.0    -1.0  
1350          0.0        -1.0           -1.0                0.0     1.0  
1351          0.0        -1.0            1.0                0.0     1.0  
1352          0.0        -1.0           -1.0                0.0    -1.0  

[1353 rows x 10 columns]

In [17]:
ds.dtypes

SFH                  float64
popUpWidnow          float64
SSLfinal_State       float64
Request_URL          float64
URL_of_Anchor        float64
web_traffic          float64
URL_Length           float64
age_of_domain        float64
having_IP_Address    float64
Result               float64
dtype: object

# Splitting the data

In [18]:
#Splitting data as independent and dependent 
#removing index column in independent dataset
x=ds.iloc[:,1:31].values
y=ds.iloc[:, -1].values 
print(x,y)

[[-1.  1. -1. ...  1.  0.  0.]
 [-1. -1. -1. ...  1.  1.  1.]
 [-1.  0.  0. ...  1.  0.  1.]
 ...
 [ 0. -1. -1. ... -1.  0.  1.]
 [ 0.  1.  0. ...  1.  0.  1.]
 [ 0.  1.  1. ... -1.  0. -1.]] [ 0.  1.  1. ...  1.  1. -1.]


In [19]:
#Splitting data into train and test 
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)